### ISSUE TITLE
Branch alphago: MCTS actions become invalid in the future

### ISSUE THREAD

**Issue by Theomat** [Theomat/go-enseirb-2020#1]
Fix that at some point there is always this issue:
```
Traceback (most recent call last):
  File "namedGame.py", line 56, in <module>
    move = players[nextplayer].getPlayerMove() # The move must be given by "A1", ... "J8" string coordinates (not as an internal move)
  File "/home/theory/Development/school/go-enseirb-2020/nn/src/mcts_nn_player.py", line 70, in getPlayerMove
    self._board.push(action)
  File "/home/theory/Development/school/go-enseirb-2020/nn/src/Goban.py", line 287, in push
    return self.play_move(m)
  File "/home/theory/Development/school/go-enseirb-2020/nn/src/Goban.py", line 250, in play_move
    captured = self._put_stone(fcoord, self._nextPlayer)
  File "/home/theory/Development/school/go-enseirb-2020/nn/src/Goban.py", line 418, in _put_stone
    self._empties.remove(fcoord)
KeyError: 3
```
3 changing depending on runs.

**Comment by Theomat** [comment]
Fixed: the root node wasn't updated :smile:
